spring.application.name=codechella
spring.flyway.url=${URLJDBC}
spring.flyway.user=${USERNAME}
spring.flyway.password=${PASSWORD}

spring.r2dbc.url=${URLR2DBC}
spring.r2dbc.username=${USERNAME}
spring.r2dbc.password=${PASSWORD}
